# Generated by Django 3.1.2 on 2020-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengelola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajar',
            name='biaya',
            field=models.IntegerField(max_length=10),
        ),
    ]
