# Generated by Django 2.2 on 2020-11-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengelola', '0002_auto_20201111_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajar',
            name='biaya',
            field=models.IntegerField(),
        ),
    ]
