# Generated by Django 2.2 on 2020-11-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengelola', '0003_auto_20201112_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='murid',
            old_name='Malamat',
            new_name='alamat',
        ),
    ]
