# Generated by Django 3.1.2 on 2020-11-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KtgAmpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='pengajar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('no', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=225)),
                ('biaya', models.DecimalField(decimal_places=10, max_digits=10)),
                ('kelamin', models.BooleanField(default=True)),
                ('usia', models.IntegerField()),
                ('catatan', models.TextField(null=True)),
                ('foto', models.ImageField(upload_to='img/')),
                ('portofolio', models.FileField(upload_to='document/')),
                ('ampu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengelola.ktgampu')),
            ],
        ),
        migrations.CreateModel(
            name='murid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('Malamat', models.CharField(max_length=225)),
                ('no', models.CharField(max_length=15)),
                ('kelamin', models.BooleanField(default=True)),
                ('pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengelola.ktgampu')),
            ],
        ),
    ]
