# Generated by Django 2.2 on 2020-11-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0006_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=25)),
                ('rilis', models.DateField()),
                ('description', models.TextField(null=True)),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.Genre')),
                ('kualitas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.Format')),
            ],
        ),
    ]
