# Generated by Django 2.2 on 2020-11-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0006_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatManga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nformat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=25)),
                ('rilis', models.DateField()),
                ('pengarang', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('baca', models.CharField(max_length=25)),
                ('description', models.TextField(null=True)),
                ('formatM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manga.FormatManga')),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.Genre')),
            ],
        ),
    ]
