# Generated by Django 2.2 on 2020-10-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=25)),
                ('tahun', models.CharField(max_length=100)),
                ('jumlah_episode', models.IntegerField(max_length=25)),
                ('genre_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime.Genre')),
            ],
        ),
    ]
