# Generated by Django 2.2 on 2020-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='jumlah_episode',
            field=models.IntegerField(null=True),
        ),
    ]
