# Generated by Django 2.2 on 2020-11-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_auto_20201029_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='download',
            field=models.TextField(null=True),
        ),
    ]
