# Generated by Django 2.2 on 2020-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='download',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
