# Generated by Django 2.2 on 2020-11-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_auto_20201102_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
